spring:
  devtools:
    restart:
      enabled: true

openai-service:
<<<<<<< HEAD
<<<<<<< HEAD
  api-key:
=======
  api-key:
>>>>>>> 568cfc1 (open ai키 secret설정)
=======
  api-key:
>>>>>>> 1945d59 (시크릿 설정 제거, 키제거)
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions